define(function(require){
    /* generated by mengma @2018-12-16 11:54 */
    var dialogid = 'dialog-'+mwt.genId();
    var form,dialog,params,callback;
    
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('fname',new MWT.TextField({
            type        : 'text',
            render      : 'fm-fname'+dialogid,
            value       : '', 
            placeholder : '',
            empty       : false,
            errmsg      : "请输入字段名称,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('ftype',new MWT.SelectField({
            render      : 'fm-ftype'+dialogid,
            options     : dict.get_options('fieldType'),
            value       : '1'
        }));
        form.addField('fdesc',new MWT.TextField({
            type        : 'text',
            render      : 'fm-fdesc'+dialogid,
            value       : '', 
            placeholder : '',
            empty       : true,
            errmsg      : "请输入字段描述,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));

        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '对话框',
            form      : form,
            style     : 'height:220px;width:500px;',
            bodyStyle : 'padding:10px;',
            body : '<table class="mwt-formtab">'+
               '<tr>'+
                 '<td width="90">字段名称 <b style="color:red">*</b></td>'+
                 '<td><div id="fm-fname'+dialogid+'"></div></td>'+
                 '<td class="tips" width="20"></td>'+
               '</tr>'+
               '<tr>'+
                 '<td>字段类型 <b style="color:red">*</b></td>'+
                 '<td><div id="fm-ftype'+dialogid+'"></div></td>'+
                 '<td class="tips"></td>'+
               '</tr>'+
               '<tr>'+
                 '<td>备注</td>'+
                 '<td><div id="fm-fdesc'+dialogid+'"></div></td>'+
                 '<td class="tips"></td>'+
               '</tr>'+
            '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.fid) {
                dialog.setTitle("编辑字段");
                form.set(params);
            } else {
                dialog.setTitle("添加字段");
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.fid = params.fid;
            data.tid = params.tid;
            ajax.post('topic&action=saveFields',data,function(res){
                if (res.errno!=0) mwt.notify(res.errmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
