define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid,topicId;
    var dialog = require('./dialog');
    var o={};
    
    o.init = function(domid,_topicId){
        gridid = domid;
        topicId = _topicId;
        store = new mwt.Store({
            proxy: new mwt.MemoryProxy({
                data: []
            })
        });
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            // cls         : 'ulgrid',
            pagebar     : false,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : true,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            //position    : 'fixed',  //!< 位置(relative:相对位置,其他:固定头部和尾部)
            emptyMsg    : textblock.empty(),
            bodyStyle   : '', 
            tbarStyle   : 'margin-bottom:-1px;background:none;',
            tbar: [
                {label:lan('add'),cls:'mwt-btn-primary',handler:function(){
                    dialog.open({id:0,tid:topicId},o.query);
                }}
            ],
            cm: new MWT.Grid.ColumnModel([
                {head:'',dataIndex:'store_index',width:40,align:'right',sort:false,render:function(v,item){
                    return (v+1)+'.';
                }},
                {head:lan(['card','name']),dataIndex:'cname',align:'left',sort:false,render:function(v,item){
                    return v;
                }},/*
                {head:'正面代码',dataIndex:'front_code',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'背面代码',dataIndex:'back_code',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'格式刷代码',dataIndex:'format_code',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'卡片顺序',dataIndex:'display_order',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'',dataIndex:'id',align:'right',sort:false,render:function(v,item){
                    var cls = 'mwt-btn mwt-btn-default mwt-btn-xs';
                    var code = '<div class="mwt-btn-group-radius">'+
                            '<button class="'+cls+'" name="editbtn-'+gridid+'" data-id="'+v+'">'+
                                '<i class="icon icon-setting"></i></button>'+
                            '<button class="'+cls+'" name="delbtn-'+gridid+'" data-id="'+v+'">'+
                                '<i class="icon icon-trash"></i></button>'+
                        '</div>';
                    return code;
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 启用开关
            jQuery('[name=adenable]').unbind('change').change(function(){
                var id = jQuery(this).data('dtname');
                var enable = jQuery(this).is(':checked') ? 1 : 0;
                ajax.post('t_cards&action=setEnable',{id:id,enabled:enable},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                    mwt.notify('已保存',1500,'success');
                });
            });
        });
        grid.create();
        o.query();
    };

    // 查询
    o.query = function() {
        var cards = require('model/topic_cards').syncLoad(topicId);
        store.proxy.data = cards;
        store.load();
    };

    // 编辑按钮点击事件
    function editbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        var item = grid.getRecord('id',id);
        dialog.open(item,o.query);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('topic&action=removeCard',{id:id},function(res){
                if (res.errno!=0) mwt.alert(res.errmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
