define(function(require){
    /* generated by mengma @2018-12-16 00:39 */
    var dialogid = 'dialog-'+mwt.genId();
    var form,dialog,params,callback;
    
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('name',new MWT.TextField({
            type        : 'text',
            render      : 'fm-name'+dialogid,
            value       : '', 
            placeholder : '',
            empty       : false,
            errmsg      : "请输入单元名称,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('description',new MWT.TextField({
            type        : 'text',
            render      : 'fm-description'+dialogid,
            value       : '', 
            placeholder : '',
            empty       : true,
            errmsg      : "请输入单元描述,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));

        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '对话框',
            form      : form,
            style     : 'width:400px;',
            bodyStyle : 'padding:10px;height:150px;',
            body : '<table class="mwt-formtab">'+
               '<tr>'+
                 '<td width="90">单元名称 <b style="color:red">*</b></td>'+
                 '<td><div id="fm-name'+dialogid+'"></div></td>'+
                 '<td class="tips" width="20"></td>'+
               '</tr>'+
               '<tr>'+
                 '<td>单元描述</td>'+
                 '<td><div id="fm-description'+dialogid+'"></div></td>'+
                 '<td class="tips"></td>'+
               '</tr>'+
            '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.id) {
                dialog.setTitle("编辑单元");
                form.set(params);
            } else {
                dialog.setTitle("添加单元");
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.id = params.id;
            data.tid = params.tid;
            ajax.post('topic&action=saveUnit',data,function(res){
                if (res.errno!=0) mwt.notify(res.errmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
