define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid,activeUid;
    var dialog = require('./unit_dialog');
    var o={};
    
    o.init = function(domid,topicInfo){
        gridid = domid;
        store = new mwt.Store({
            proxy: new mwt.HttpProxy({
                //beforeLoad : store_before_load,
                //afterLoad  : store_after_load,
                url : ajax.getAjaxUrl("topic&action=queryUnit&tid="+topicInfo.topicId),
            })
        });
        store.on('load',function(){
            store.root.unshift({id:0,name:'全部单元',tid:topicInfo.topicId});
        });
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            cls         : 'mwt-table ulgrid',
            pagebar     : false,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : false,     //!< 斑马纹
            noheader    : true,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            position    : 'fixed',  //!< 位置(relative:相对位置,其他:固定头部和尾部)
            bodyStyle   : 'background:#fff',
            tbarStyle   : 'margin-bottom:-1px;',
            emptyMsg    : textblock.empty(),
            rowclick    : rowClick,
            tbar: [
                '<label class="head-title">单元</label>',
                '->',
                {label:iconlabel.plus(''),cls:'mwt-btn-primary tbtn',handler:function(){
                    dialog.open({id:0,tid:topicInfo.topicId},o.query);
                }}
            ],
            cm: new MWT.Grid.ColumnModel([
                {head:'单元',dataIndex:'name',align:'left',sort:false,render:function(v,item){
                    if (item.id==0) {
                        return '<i class="fa fa-folder"></i> '+v;
                    }
                    return '<i style="margin-left:15px;" class="fa fa-folder"></i> '+v;
                }},
                /*{head:'顺序',dataIndex:'display_order',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'操作',dataIndex:'id',width:30,align:'right',sort:false,render:function(v,item){
                    if (v==0) return '';
                    var cls = 'grida';
                    var editbtn = '<a class="'+cls+'" name="editbtn-'+gridid+'" data-id="'+v+'" '+
                        ' style="color:#999;" href="javascript:;">'+
                            '<i class="icon icon-setting"></i>'+
                        '</a>';
                    // var delbtn = '<a name="delbtn-'+gridid+'" data-id="'+v+'" href="javascript:;">删除</a>';
                    var btns = [editbtn];
                    return btns.join("&nbsp;&nbsp;");
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 启用开关
            jQuery('[name=adenable]').unbind('change').change(function(){
                var id = jQuery(this).data('dtname');
                var enable = jQuery(this).is(':checked') ? 1 : 0;
                ajax.post('t_fields&action=setEnable',{id:id,enabled:enable},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                    mwt.notify('已保存',1500,'success');
                });
            });

            // 选中一个单元
            var idx = store.indexOf('id',activeUid);
            if (idx<0) {
                activeUid = 0;
                idx = 0;
            }
            var item = store.get(idx);
            rowClick(item);
        });
        grid.create();
        o.query();
    };

    // 查询
    o.query = function() {
        store.baseParams = {
            key: '', //mwt.get_value("so-key-"+gridid)
        };
        grid.load();
    };

    // 点击行
    function rowClick(item) {
        require("./item_panel/grid").setUnit(item);
    }


    // 编辑按钮点击事件
    function editbtnClick(e)
    {/*{{{*/
        e.stopPropagation();
        var id = jQuery(this).data('id');
        var item = grid.getRecord('id',id);
        dialog.open(item,o.query);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('t_fields&action=remove',{id:id},function(res){
                if (res.retcode!=0) mwt.alert(res.retmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
