define(function(require){
    /* generated by mengma @2018-12-16 00:39 */
    var dialogid = 'dialog-unit-item';
    var form,dialog,params,topicFields,callback;
    var flag = 0;

    // 文本字段
    function get_textfield(divid,value) {
        return new MWT.TextField({
            type        : 'text',
            render      : divid,
            value       : value,
            placeholder : '',
            empty       : false,
            checkfun    : function(v){return v.length<=1024;}
        });
    }

    // 显示表单（根据字段配置渲染）
    function showForm() {
        var domid = dialogid+'-dialog-content';
        // 必须先定义卡片字段
        if (!topicFields || !topicFields.length) {
            textblock.empty(lan('no_fields_defined'),domid);
            flag = 0;
            return;
        }
        // 必须定义单元
        var unitOptions = require('model/topic_units').getOptions(params.topic_id);
        if (!unitOptions || !unitOptions.length) {
            textblock.empty(lan('no_unit_defined'),domid);
            flag = 0;
            return;
        }

        flag = 1;
        // 表单字段
        form = new MWT.Form();
        form.addField('unit_id',new MWT.SelectField({
            render  : 'fm-unitid'+domid,
            options : require('model/topic_units').getOptions(params.topic_id),
            value   : params.unit_id,
        }));
        var trs = [];
        for (var i=0;i<topicFields.length;++i) {
            var item = topicFields[i];
            var k = item.k;
            var nc = '<b style="color:red">*</b> ';
            var code = '<tr>'+
                    '<th colspan="2" style="padding-top: 10px;">'+nc+item.k+':<div id="fm-'+item.k+'"></div></th>'+
                '</tr>';
            trs.push(code);
            // 根据字段类型使用不同控件
            var v = '';
            if (params.fields && params.fields[i]) {
                v = params.fields[i];
            }
            switch(parseInt(item.type)) {
                default: form.addField(k,get_textfield('fm-'+k,v)); break;
            }
        }
        var code = '<table class="mwt-formtab">'+
                '<tr><th width="60">'+lan('unit')+'</th>'+
                    '<td><div id="fm-unitid'+domid+'"></div></td>'+
                '</tr>'+
                trs.join('')+
            '</table>';
        jQuery('#'+domid).html(code);
        form.create();

        //

    }

    function init_dialog() 
    {/*{{{*/
        dialog = new MWT.Dialog({
            render    : dialogid,
            title     : 'Data Item',
            fullscreen: true,
            style     : 'left:20%;right:20%;',
            bodyStyle : 'padding:5px 10px 10px;background:#eee',
            body : '',
            buttons : [
                {label:lan('submit'),cls:'mwt-btn-primary',handler:submitClick},
                {label:lan('cancel'),type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            showForm();
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_topicFields,_callback){
        params = _params;
        topicFields = _topicFields;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };

    function submitClick() {
        if (!flag) {
            mwt.notify(lan('no_fields_defined'),1500,'danger');
            return;
        }
        var map = form.getData();
        var fds = [];
        for (var i=0;i<topicFields.length;++i) {
            var k = topicFields[i].k;
            fds.push(map[k]);
        }
        var data = {
            id: params.id,
            unit_id: mwt.get_select_value('fm-unitid'+dialogid+'-dialog-contentsel'),
            topic_id: params.topic_id,
            fields: fds,
        };
        ajax.post('topic&action=saveUnitItem',data,function(res){
            if (res.errno!=0) mwt.alert(res.errmsg);
            else {
                dialog.close();
                if(callback) callback();
            }
        });
    }

    return o;
});
