define(function(require){
    /* generated by mengma @2018-12-16 00:39 */
    var dialogid = 'dialog-unit-item-move';
    var form,dialog,params,topicFields,callback;
    var records,topicId;

    // 显示表单（根据字段配置渲染）
    function showForm() {
        var domid = dialogid+'-dialog-content';
        // 必须定义单元
        var unitOptions = require('model/topic_units').getOptions(topicId);
        if (!unitOptions || !unitOptions.length) {
            textblock.empty(lan('no_unit_defined'),domid);
            return;
        }
        // 表单字段
        form = new MWT.Form();
        form.addField('unit_id',new MWT.SelectField({
            render  : 'fm-unitid'+domid,
            style   : 'border-radius:0',
            options : unitOptions,
        }));
        var code = '<table class="mwt-formtab">'+
                '<tr><th>'+lan(['move_to','unit'])+': </th></tr>'+
                '<tr><td><div id="fm-unitid'+domid+'"></div></td></tr>'+
            '</table>';
        jQuery('#'+domid).html(code);
        form.create();
    }

    function init_dialog() 
    {/*{{{*/
        dialog = new MWT.Dialog({
            render    : dialogid,
            title     : 'Move Data',
            fullscreen: false,
            style     : 'width:500px',
            bodyStyle : 'padding:5px 10px 10px;background:#eee',
            body : '',
            buttons : [
                {label:lan('submit'),cls:'mwt-btn-primary',handler:submitClick},
                {label:lan('cancel'),type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            showForm();
        });
    }/*}}}*/

    var o={};
    o.open=function(_records,_topicId,_callback){
        records = _records;
        topicId = _topicId;
        callback = _callback;
        if (!records || !records.length) return;
        if (!dialog) init_dialog();
        dialog.open();
    };

    function submitClick() {
        var data = {
            unit_id: mwt.get_select_value('fm-unitid'+dialogid+'-dialog-contentsel'),
            ids : [],
        };
        for (var i=0;i<records.length;++i) {
            var rd = records[i];
            data.ids.push(rd.id);
        }
        ajax.post('topic&action=moveItemsUnit',data,function(res){
            if (res.errno!=0) mwt.alert(res.errmsg);
            else {
                dialog.close();
                if(callback) callback();
            }
        });
    }

    return o;
});
