define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var gridid;
    var o={};
    
    o.init = function(domid){
        gridid = domid;
        o.query();
    };

    // 查询
    o.query = function() {
        ajax.post('study&action=queryMyStudy',{},function(res){
            if (res.errno!=0) mwt.alert(res.errmsg);
            else showTable(res.data);
        });
    };

    function showTable(data) {
        var topics = [];
        for (var topicId in data) {
            var item = data[topicId];
            var code = '<tr class="partition">'+
                    '<td colspan="7">'+item.topicName+'</td>'+
                '</tr>'+
                '<tbody>'+
                    getUnits(item.studyList)+
                '</tbody>';
            topics.push(code);
        }
        var code = '<table class="study-tab">'+
                '<thead>'+
                    '<tr>'+
                        '<th>'+lan('topic')+'</th>'+
                        '<th class="rt">'+lan('stat_new')+'</th>'+
                        '<th class="rt">'+lan('stat_learning')+'</th>'+
                        '<th class="rt">'+lan('stat_review')+'</th>'+
                        '<th class="rt"></th>'+
                    '</tr>'+
                '</thead>'+
                topics.join('')+
            '</table>';
        jQuery('#'+gridid).html(code);
    }

    function getUnits(list) {
        var trs = [];
        for (var i=0;i<list.length;++i) {
            var studyInfo = list[i];
            var code = '<tr>'+
                    '<td style="padding-left:30px;"><i class="fa fa-folder"></i> '+studyInfo.unitName+'</td>'+
                    '<td class="rt"><b class="stat-new">'+studyInfo.statNew+'</b></td>'+
                    '<td class="rt"><b class="stat-learning">'+studyInfo.statLearning+'</b></td>'+
                    '<td class="rt"><b class="stat-review">'+studyInfo.statReview+'</b></td>'+
                    '<td class="rt">'+
                        '<a href="'+studyInfo.studyUrl+'" target="_blank" '+
                            'class="mwt-btn mwt-btn-default mwt-btn-xs">'+lan('study')+'</a>'+
                        '&nbsp;&nbsp;'+
                        '<a href="'+studyInfo.viewUrl+'" target="_blank" '+
                            'class="mwt-btn mwt-btn-default mwt-btn-xs">'+lan('view')+'</a>'+
                    '</td>'+
                '</tr>';
            trs.push(code);
        }
        return trs.join('');
    }


    return o;
});
