define(function(require){
    /* generated by mengma @2018-12-15 08:34 */
    var dialogid = 'dialog-'+mwt.genId();
    var form,dialog,params,callback;
    
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('cateid',new MWT.SelectField({
            render      : 'fm-cateid'+dialogid,
            options     : dict.get_options("topicCate"),
            value       : '0'
        }));
        form.addField('tname',new MWT.TextField({
            type        : 'text',
            render      : 'fm-tname'+dialogid,
            value       : '', 
            placeholder : '',
            empty       : false,
            errmsg      : "请输入名称,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('description',new MWT.TextField({
            type        : 'text',
            render      : 'fm-description'+dialogid,
            value       : '', 
            placeholder : '',
            empty       : true,
            errmsg      : "请输入描述,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        /*
        form.addField('status',new MWT.TextField({
            type        : 'number',
            render      : 'fm-status'+dialogid,
            value       : '0', 
            placeholder : '请输入状态(1:私有,2:公开)',
            empty       : false,
            errmsg      : "请输入状态(1:私有,2:公开),不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));*/

        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '对话框',
            form      : form,
            //animate   : 'slideRight',
            top : 50,
            style     : 'height:200px;width:400px;',
            //bodyStyle : 'padding:10px;',
            body : '<table class="mwt-formtab">'+
               '<tr>'+
                 '<td width="70">分类 <b style="color:red">*</b></td>'+
                 '<td><div id="fm-cateid'+dialogid+'"></div></td>'+
                 '<td width="20" class="tips"></td>'+
               '</tr>'+
               '<tr>'+
                 '<td>名称 <b style="color:red">*</b></td>'+
                 '<td><div id="fm-tname'+dialogid+'"></div></td>'+
                 '<td class="tips"></td>'+
               '</tr>'+
               '<tr>'+
                 '<td>备注</td>'+
                 '<td><div id="fm-description'+dialogid+'"></div></td>'+
                 '<td class="tips"></td>'+
               '</tr>'+
/*               '<tr>'+
                 '<td>状态(1:私有,2:公开) <b style="color:red">*</b></td>'+
                 '<td><div id="fm-status'+dialogid+'"></div></td>'+
                 '<td class="tips"></td>'+
               '</tr>'+
               */
            '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.tid) {
                dialog.setTitle("编辑数据集");
                form.set(params);
            } else {
                dialog.setTitle("创建数据集");
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.tid = params.tid;
            ajax.post('topic&action=saveMyTopic',data,function(res){
                if (res.errno!=0) mwt.notify(res.errmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
