define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,domid,topicInfo;
    var o={};


    function getTypeSelect(v) {
        var opts = [];
        var ls = dict.get_options('fieldType');
        for (var i=0;i<ls.length;++i) {
            var im = ls[i];
            var selected = im.value==v ? ' selected' : '';
            var opt = '<option value="'+im.value+'"'+selected+'>'+im.text+'</option>';
            opts.push(opt);
        }
        return '<select class="mwt-field" name="ftype'+domid+'">'+opts.join('')+'</select>';
    }

    function showTable() {
        var trs = [];
        for (var i=0;i<store.size(); ++i) {
            var im = store.get(i);
            var code = '<tr>'+
                '<td><input type="text" name="fk-'+domid+'" value="'+im.k+'" class="mwt-field"></td>'+
                '<td>'+getTypeSelect(im.type)+'</td>'+
                '<td style="text-align: right;">'+
                    '<a href="javascript:;" data-idx="'+i+'" name="delbtn'+domid+'">'+
                        lan('delete')+'</a></td>'+
                '</tr>';
            trs.push(code);
        }

        var code = '<table class="edit-tab">'+
                '<tr>'+
                    '<th>'+lan('field')+'</th>'+
                    '<th>'+lan(['field','type'])+'</th>'+
                    '<th></th>'+
                '</tr>'+
                trs.join('')+
            '</table>';
        jQuery('#center'+domid).html(code);

        // 删除一行
        jQuery('[name=delbtn'+domid+']').unbind('click').click(function(){
            var idx = jQuery(this).data('idx');
            store.remove(idx);
        });
    }

    // 添加一个字段
    function addOne() {
        var item = {
            k: '',
            type: 1
        };
        store.push(item);
    }

    // 获取数据
    function getData() {
        var fields = [];
        var n = jQuery('[name=fk-'+domid+']').length;
        for (var i=0;i<n;++i) {
            var jk = jQuery('[name=fk-'+domid+']').eq(i);
            var k = jk.val().trim();
            if (k=='') {
                jk.val('').focus();
                throw "field is null";
            }
            var item = {
                k: k,
                type: jQuery('[name=ftype'+domid+']').eq(i).val(),
            };
            fields.push(item);
        }
        return fields;
    }


    function save() {
        try {
            var params = {
                id: topicInfo.topicId,
                fields: getData(),
            };
            ajax.post('topic&action=saveFields',params,function(res){
                if (res.errno!=0) { mwt.alert(res.errmsg); }
                else {
                    mwt.notify(lan('saved'),1500,'success');
                    topicInfo.fields = params.fields;
                }
            });
        } catch (e) {
            return;
        }
    }

    o.init = function(_domid,_topicInfo){
        domid = _domid;
        topicInfo = _topicInfo;

        new mwt.BorderLayout({
            render : domid,
            items : [
                {id:'north'+domid, region:'north',height:42,style:"padding-top:5px;overflow:hidden;"},
                {id:'center'+domid,region:'center'}
            ]
        }).init();

        new mwt.ToolBar({
            render : 'north'+domid,
            style : 'background:none',
            items  : [
                {label:lan('add'),cls:'mwt-btn-primary',handler:addOne},
                {label:lan('save'),cls:'mwt-btn-primary',handler:save},
            ]
        }).create();

        store=new mwt.Store({
            proxy: new mwt.MemoryProxy({
                data: topicInfo.fields
            })
        });
        store.on("load",showTable);
        store.load();
    };

    return o;
});
