define(function(require){
    /* generated by mengma @2018-12-16 12:53 */
    var dialogid = 'dialog-'+mwt.genId();
    var form,dialog,params,callback;
    
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('cname',new MWT.TextField({
            type        : 'text',
            render      : 'fm-cname'+dialogid,
            value       : 'Front -> Back',
            placeholder : '',
            empty       : false,
            errmsg      : "请输入卡片名称,不超过128个字符",
            checkfun    : function(v){return v.length<=128;}
        }));
        form.addField('front_code',new MWT.TextField({
            type        : 'textarea',
            style       : 'height:130px;',
            render      : 'fm-front_code'+dialogid,
            value       : '{{Front}}',
            placeholder : '',
            empty       : false,
            errmsg      : "请输入正面代码,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('format_code',new MWT.TextField({
            type        : 'textarea',
            render      : 'fm-format_code'+dialogid,
            style       : 'height:130px;',
            value       : '.card {font-size:18px;}',
            placeholder : '',
            empty       : false,
            errmsg      : "请输入格式刷代码,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('back_code',new MWT.TextField({
            type        : 'textarea',
            render      : 'fm-back_code'+dialogid,
            style       : 'height:130px;',
            value       : '{{Back}}',
            placeholder : '',
            empty       : false,
            errmsg      : "请输入背面代码,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));

        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '对话框',
            form      : form,
            //fullscreen: true,
            // animate   : 'slideRight',
            top: 20,
            style     : 'width:800px;height:600px;',
            bodyStyle : 'padding:10px;background:#eee',
            body : '<table class="mwt-formtab">'+
                  '<tr>'+
                    '<td width="90">卡片名称 <b style="color:red">*</b></td>'+
                    '<td><div id="fm-cname'+dialogid+'"></div></td>'+
                    '<td width="300">预览</td>'+
                  '</tr>'+
                  '<tr>'+
                    '<td colspan="2">正面代码 <b style="color:red">*</b>'+
                        '<div id="fm-front_code'+dialogid+'"></div></td>'+
                    '<td></td>'+
                  '</tr>'+
                  '<tr>'+
                    '<td colspan="2">格式刷 <b style="color:red">*</b>'+
                      '<div id="fm-format_code'+dialogid+'"></div></td>'+
                    '<td></td>'+
                  '</tr>'+
                  '<tr>'+
                    '<td colspan="2">背面代码 <b style="color:red">*</b>'+
                        '<div id="fm-back_code'+dialogid+'"></div></td>'+
                    '<td></td>'+
                  '</tr>'+
                '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.cid) {
                dialog.setTitle("编辑卡片");
                form.set(params);
            } else {
                dialog.setTitle("添加卡片");
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.cname = dz_post_encode(data.cname);
            data.front_code = dz_post_encode(data.front_code);
            data.format_code = dz_post_encode(data.format_code);
            data.back_code = dz_post_encode(data.back_code);
            data.cid = params.cid;
            data.tid = params.tid;
            ajax.post('topic&action=saveCard',data,function(res){
                if (res.errno!=0) mwt.notify(res.errmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
