<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-12-15 10:27
 * @usage: C::t('#ankix#topic')->fun();
 **/
class table_topic_unit
{
    private $table = "topic_unit";
    private $pdo;


    public function __construct() {
        $this->pdo = ankix_env::getpdo('db_ankix_base');
    }

    // 获取单元信息及单元的主题信息
    public function getUnitInfo($unitId)
    {/*{{{*/
        $sql = <<<EOF
SELECT 
a.id as unitId,
a.name as unitName,
a.cover_img as coverImage,
a.description as unitDesc,
a.status as unitStatus,
b.id as topicId,
b.tname as topicName,
b.fields as cardFields,
b.options
FROM {$this->table} as a
LEFT JOIN topic as b ON b.id=a.tid
WHERE a.id='{$unitId}' AND a.isdel=0 AND b.isdel=0
EOF;
        $res = $this->pdo->queryFirst($sql);
        if (!empty($res)) {
            $res["cardFields"] = json_decode($res['cardFields']);
            $res["options"] = json_decode($res['options']);

            $res["cardStyles"] = C::t('#ankix#topic_cards')->getAll($res['topicId']);
        }
        return $res;
    }/*}}}*/


    // 获取Topic
    public function getByTopicId($tid)
    {/*{{{*/
        $sql = <<<EOF
SELECT 
a.tid as topicId,a.tname as topicName,a.description,
a.cateid as cateId,
b.cname as cateName,
a.status,a.uid,
a.create_time as createTime
FROM {$this->table} as a
LEFT JOIN topic_category as b ON b.cid=a.cateid
WHERE a.tid='$tid' AND a.isdel=0;
EOF;
        return $this->pdo->queryFirst($sql);
    }/*}}}*/


    // 查询接口
    public function query()
    {/*{{{*/
        global  $_G;
        $uid = $_G['uid'];
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $key   = ankix_validate::getNCParameter('key','key','string');
        $tid   = ankix_validate::getNCParameter('tid','tid','integer');
        $sort  = ankix_validate::getOPParameter('sort','sort','string',1024,'id');
        $dir   = ankix_validate::getOPParameter('dir','dir','string',1024,'ASC');
        $start = ankix_validate::getOPParameter('start','start','integer',1024,0);
        $limit = ankix_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "a.tid='$tid' AND a.isdel=0";
        if ($key!="") $where.=" AND (a.name like '%$key%')";
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS 
a.*
FROM {$this->table} as a
WHERE $where
ORDER BY a.$sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = $this->pdo->queryAll($sql);
        $row = $this->pdo->queryFirst("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        //////////////////////////////////////////
        //
        foreach ($return["root"] as &$item) {
            $item["unit"] = ankix_utils::encodeId($item[id]);
        }
        //////////////////////////////////////////
        return $return;
    }/*}}}*/

    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = ankix_validate::getNCParameter('id','id','integer');
        $record = array (
            'name' => ankix_validate::getNCParameter('name','name','string',50),
            'description' => ankix_validate::getNCParameter('description','description','string',1024),
            'cover_img' => ankix_validate::getNCParameter('cover_img','cover_img','string',1024),
        ); 
        if ($id==0) {
            $record['tid'] = ankix_validate::getNCParameter('tid','tid','integer');
            $record['status'] = 1;
            $record['create_time'] = date('Y-m-d H:i:s');
            return $this->pdo->insert($this->table,$record);
        } else {
            return $this->pdo->update($this->table,$record,array("id='$id'"));
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = ankix_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/

    // 保存状态
    public function saveStatus()
    {/*{{{*/
        $id = ankix_validate::getNCParameter('id','id','integer');
        $record = array (
            'status' => ankix_validate::getNCParameter('status','status','integer'),
        );
        return $this->pdo->update($this->table,$record,array("id='$id'"));
    }/*}}}*/


}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
