<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-12-15 10:27
 * @usage: C::t('#ankix#language')->fun();
 **/
class table_language
{
    private $table = "language";
    private $pdo;


    public function __construct() {
        $this->pdo = ankix_env::getpdo('db_ankix_base');
    }

    // 获取某语言包的全部数据
    public function loadAll($lang) 
    {
        $sql = "SELECT k,$lang as v FROM {$this->table}";
        $res = $this->pdo->queryAll($sql);
        $resMap = array();
        foreach ($res as &$item) {
            $k = $item['k'];
            $v = mb_strtolower($item['v'],'UTF8');
            if ($v=='') $v = $k;
            $resMap[$k] = $item['v'];
        }
        return $resMap;
    }

}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
