<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-12-15 10:27
 * @usage: C::t('#ankix#study')->fun();
 **/
class table_study
{
    private $table = "study";
    private $pdo;


    public function __construct() {
        $this->pdo = ankix_env::getpdo('db_ankix_base');
    }

    // 获取我购买的全部主题
    public function getAllMyTopics($uid) 
    {
        $sql = <<<EOF
SELECT 
distinct c.id as topicId,
c.tname as topicName,
c.cover_img as topicImg,
c.description as topicDesc
FROM study as a
LEFT JOIN topic_unit as b ON b.id=a.unit_id
LEFT JOIN topic as c ON c.id=b.tid
EOF;
    }

    // 获取我的全部单元
    public function getAllMyUnits($uid)
    {
        $sql = <<<EOF
SELECT 
c.id as topicId,
c.cateid as topicCateId,
c.tname as topicName,
c.cover_img as topicImg,
c.description as topicDesc,
b.id as unitId,
b.name as unitName,
b.cover_img as unitImg,
b.description as unitDesc,
a.id as studyId,
a.stat_new as statNew,
a.stat_learning as statLearning,
a.stat_review as statReview,
a.uid
FROM study as a
LEFT JOIN topic_unit as b ON b.id=a.unit_id
LEFT JOIN topic as c ON c.id=b.tid
WHERE a.uid='$uid' AND a.isdel=0
EOF;
        $res = $this->pdo->queryAll($sql);
        $resMap = array();

        $mUrl = C::m('#ankix#ankix_url');
        foreach ($res as &$item) {
            $topicId = $item['topicId'];
            if (!isset($resMap[$topicId])) {
                $resMap[$topicId] = array (
                    'topicName' => $item['topicName'],
                    'topicImg' => $item['topicImg'],
                    'topicDesc' => $item['topicDesc'],
                    'topicCateId' => $item['topicCateId'],
                    'studyList' => array(),
                );
            }
            $resMap[$topicId]['studyList'][] = array (
                'studyId' => $item['studyId'],
                'unitId' => $item['unitId'],
                'unitName' => $item['unitName'],
                'unitImg' => $item['unitImg'],
                'statNew' => intval($item['statNew']),
                'statLearning' => intval($item['statLearning']),
                'statReview' => intval($item['statReview']),
                'uid' => $item['uid'],
                'viewUrl' => $mUrl->getUnitViewUrl($item['unitId']),
            );
        }
        return $resMap;
    }
}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
